# Generated by Django 3.2.13 on 2022-07-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='phone',
            new_name='image',
        ),
    ]
