# Generated by Django 3.2.13 on 2022-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20220604_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentitems',
            name='type',
            field=models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='income', max_length=7),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='title',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
