# Generated by Django 3.2.13 on 2022-06-13 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20220611_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='indications',
            field=models.DecimalField(decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('accounted', 'Учтено'), ('accounted_for_paid', 'Учтено и оплачено'), ('zero', 'Нулевое')], default='new', max_length=20),
        ),
    ]
