# Generated by Django 3.2.13 on 2022-06-25 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220530_2034'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_auto_20220613_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('template', models.FileField(upload_to='crm/receipt-templates/')),
            ],
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_work', 'В работе'), ('done', 'Выполнено')], default='new', max_length=7),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='type_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.apartment'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.services'),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(choices=[('paid', 'Оплачена'), ('partially_paid', 'Частично оплачена'), ('not_paid', 'Не оплачена')], default='not_paid', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='pricetariffservices',
            unique_together={('tariff', 'services')},
        ),
    ]
