# Generated by Django 3.2.13 on 2022-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20220625_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemplate',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
