# Generated by Django 3.2.13 on 2022-06-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_receipttemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_account', to='crm.personalaccount'),
        ),
        migrations.AlterField(
            model_name='calculatereceiptservice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculate_receipt', to='crm.receipt'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_account', to='crm.personalaccount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_apartment', to='crm.apartment'),
        ),
        migrations.AlterField(
            model_name='receipttemplate',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
