# Generated by Django 3.2.13 on 2022-07-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20220627_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatereceiptservice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calculatereceiptservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calculatereceiptservice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calculatereceiptservice',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.services'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_apartment', to='crm.apartment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_apartment', to='crm.apartment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_account', to='crm.personalaccount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.tariff'),
        ),
    ]
